// 4.vue/vue2/basic/demo/36_src_router-link的replace属性/App.vue
<template>
  <div>
    <div class="row">
      <Banner />
    </div>
    <div class="row">
      <div class="col-xs-2 col-xs-offset-2">
        <div class="list-group">
          <!-- 原始html中我们使用a标签实现页面的跳转 -->
          <!-- <a class="list-group-item active" href="./about.html">About</a> -->
          <!-- <a class="list-group-item" href="./home.html">Home</a> -->

          <!-- Vue中借助router-link标签实现路由的切换 -->
          <router-link class="list-group-item" active-class="active" to="/about"
            >About</router-link
          >
          <router-link class="list-group-item" active-class="active" to="/home"
            >Home</router-link
          >
        </div>
      </div>
      <div class="col-xs-6">
        <div class="panel">
          <div class="panel-body">
            <!-- 指定组件的呈现位置 -->
            <router-view />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import Banner from "./components/Banner";
export default {
  name: "App",
  components: { Banner },
};
</script>

// 5.react/example/1/src/App.js
import { BrowserRouter, NavLink, Switch, Route, Redirect } from 'react-router-dom'
import Header from './components/Header'
import Home from './pages/Home'
import Hello from './pages/Hello'
import TodoList from './pages/TodoList'
import SearchGitHub from './pages/SearchGitHub/3'
import './App.css';
import './assets/css/bootstrap.css'

export default function App() {
  return (
    <BrowserRouter>
      <div className="App">
        <div className="row">
          <div className="col-xs-offset-2 col-xs-9">
            <Header />
          </div>
        </div>
        <div className="row">
          <div className="col-xs-2 col-xs-offset-2">
            <div className="list-group">
              {/* <NavLink exact className="list-group-item" to="/">Home</NavLink> */}
              <NavLink exact className="list-group-item" to="/home">Home</NavLink>
              <NavLink className="list-group-item" to="/hello">Hello</NavLink>
              <NavLink className="list-group-item" to="/todolist" >TodoList</NavLink>
              <NavLink className="list-group-item" to="/searchgithub" >SearchGitHub</NavLink>
            </div>
          </div>
          <div className="col-xs-7">
            <div className="panel">
              <div className="panel-body">
                <Switch>
                  {/* <Route exact path='/' component={Home} /> */}
                  <Route path='/home' component={Home} />
                  <Route path='/hello' component={Hello} />
                  <Route path='/todolist' component={TodoList} />
                  <Route path='/searchgithub' component={SearchGitHub} />
                  <Redirect to='/home/news' />
                </Switch>
              </div>
            </div>
          </div>
        </div>
      </div >
    </BrowserRouter>
  );
}
