// 4.vue/vue2/basic/demo/28_src_求和案例_多组件共享数据/components/Person.vue
<template>
  <div>
    <h1>人员列表</h1>
    <h3 style="color: red">Count组件求和为：{{ sum }}</h3>
    <input type="text" placeholder="请输入名字" v-model="name" />
    <button @click="add">添加</button>
    <ul>
      <li v-for="p in personList" :key="p.id">{{ p.name }}</li>
    </ul>
  </div>
</template>

<script>
import { nanoid } from "nanoid";
export default {
  name: "Person",
  data() {
    return {
      name: "",
    };
  },
  computed: {
    personList() {
      return this.$store.state.personList;
    },
    sum() {
      return this.$store.state.sum;
    },
  },
  methods: {
    add() {
      const personObj = { id: nanoid(), name: this.name };
      this.$store.commit("ADD_PERSON", personObj);
      this.name = "";
    },
  },
};
</script>

// 5.react/example/1/src/pages/ReactRedux/Person/index.jsx
import React, { Component } from 'react'
import { nanoid } from 'nanoid'
import { connect } from 'react-redux'
import { addPerson } from '../../../redux/actions/person'

class Person extends Component {

	addPerson = () => {
		const { addPerson } = this.props;
		const name = this.nameNode.value
		const age = this.ageNode.value * 1
		const personObj = { id: nanoid(), name, age }
		addPerson(personObj)
		this.nameNode.value = ''
		this.ageNode.value = ''
	}

	render() {
		const { count, person } = this.props;
		return (
			<div>
				<h2>我是Person组件,上方组件求和为{count}</h2><br/>
				<input ref={c => this.nameNode = c} type="text" placeholder="输入名字" />&emsp;
				<input ref={c => this.ageNode = c} type="text" placeholder="输入年龄" /><br/><br/>
				<button onClick={this.addPerson}>添加</button><br/><br/>
				<ul>
					{
						person.map((p) => {
							return <li key={p.id}>{p.name}--{p.age}</li>
						})
					}
				</ul>
			</div>
		)
	}
}

export default connect(
	state => ({
		person: state.person,
		count: state.count
	}),//映射状态
	{ addPerson }//映射操作状态的方法
)(Person)
