// 5.react/example/1/src/pages/SearchGitHub/1/Search/index.jsx
import React, { Component } from 'react'
import axios from 'axios'

export default class Search extends Component {

  search = () => {
    const { value: keyWord } = this.keyWordNode;
    this.props.updateSearchState({ isLoading: true, isFirst: false })
    axios.get(`/api1/search/users?q=${keyWord}`).then(
      response => {
        //请求成功后通知App更新状态
        this.props.updateSearchState({ isLoading: false, users: response.data.items })
      },
      error => {
        //请求失败后通知App更新状态
        this.props.updateSearchState({ isLoading: false, err: error.message })
      }
    )
  }

  render() {
    return (
      <section className="jumbotron">
        <h3 className="jumbotron-heading">搜索Github用户</h3>
        <div>
          <input ref={c => this.keyWordNode = c} type="text" placeholder="输入关键词点击搜索" />&nbsp;
          <button onClick={this.search}>搜索</button>
        </div>
      </section>
    )
  }
}

// 4.vue/vue2/basic/demo/21_src_github搜索案例_vue-resource/components/Search.vue
<template>
	<section class="jumbotron">
		<h3 class="jumbotron-heading">Search Github Users</h3>
		<div>
			<input type="text" placeholder="enter the name you search" v-model="keyWord" />&nbsp;
			<button @click="searchUsers">Search</button>
		</div>
	</section>
</template>

<script>
export default {
	name: 'Search',
	data() {
		return {
			keyWord: ''
		}
	},
	methods: {
		searchUsers() {
			// 请求前更新List的数据
			this.$bus.$emit('updateListData', { isLoading: true, errMsg: '', users: [], isFirst: false })
			this.$http.get(`https://api.github.com/search/users?q=${this.keyWord}`).then(
				response => {
					console.log('请求成功了')
					// 请求成功后更新List的数据
					this.$bus.$emit('updateListData', { isLoading: false, errMsg: '', users: response.data.items })
				},
				error => {
					// 请求后更新List的数据
					this.$bus.$emit('updateListData', { isLoading: false, errMsg: error.message, users: [] })
				}
			)
		}
	},
}
</script>
